In [1]:
# Linux
import torch
if torch.cuda.is_available():
	print("Cuda ready!")
	device = "cuda"
else:
	print("Cuda driver not installed, device set to CPU")
	device = "cpu"

Cuda ready!


In [2]:
print(torch.__version__)

2.4.0


In [3]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim()) # rank
t.shape
t.size()

1


torch.Size([7])

In [7]:
print(t[0],t[1],t[-1])

tensor(0.) tensor(1.) tensor(6.)


In [8]:
print(t[2:5],t[4:-1])

tensor([2., 3., 4.]) tensor([4., 5.])


In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [12]:
t[2]

tensor([7., 8., 9.])

In [14]:
t[:,-1]

tensor([ 3.,  6.,  9., 12.])

In [15]:
t = torch.FloatTensor([[1,2],[3,4]])

t.max()

tensor(4.)

In [17]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [20]:
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

ft.shape

torch.Size([2, 2, 3])

In [21]:
reshaped_ft = ft.view([3,4])

reshaped_ft.shape


torch.Size([3, 4])

In [22]:
reshaped_ft = ft.view([4,3])

reshaped_ft.shape

torch.Size([4, 3])

In [23]:
reshaped_ft = ft.view([3,-1])

reshaped_ft.shape

torch.Size([3, 4])

In [24]:
reshaped_ft = ft.view([2,2,1,3])

reshaped_ft.shape

torch.Size([2, 2, 1, 3])

In [25]:
t = np.ones([128,128])
tf = torch.FloatTensor(t)


In [30]:
tf = tf.view([128,128,1])
tf.shape

torch.Size([128, 128, 1])

In [32]:
tf = tf.squeeze()
tf.shape


torch.Size([128, 128])

In [33]:
tf = tf.view([-1,1])
tf.shape

torch.Size([16384, 1])

In [34]:
tf = tf.squeeze()
tf.shape

torch.Size([16384])

In [38]:
tf = tf.squeeze()
tf.shape

torch.Size([16384])

In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [43]:
torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [45]:
w = torch.zeros(1,requires_grad=True)
b= torch.zeros(1,requires_grad=True)

In [48]:
y_pred = x_train * w + b

In [51]:
loss = torch.mean(((y_train - y_pred) ** 2))

print(loss)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [50]:
optimizer = optim.SGD([w,b],lr=0.001)

In [52]:
optimizer.zero_grad()

loss.backward()

optimizer.step()

In [60]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2800 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2800 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2800 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2800 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2800 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2800 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2800 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2800 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2800 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2800 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2800 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2800 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2800 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2800 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2800 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2800 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2800 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2800 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2800 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2800 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2800 W: 1.997, b: 0.008 Cost: 0.000008

In [61]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [62]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [63]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3,1)

print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [64]:
x_train.shape

torch.Size([5, 3])

In [67]:
optimizer = optim.SGD(model.parameters(),lr = 1e-2)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.20f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: nan
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [68]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[nan]], grad_fn=<AddmmBackward0>)


In [93]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,3)
        self.linear2 = nn.Linear(3,1)

        self.relu = nn.ReLU()

    def forward(self,x):
        x = self.linear(x)
        x = self.relu(x)
        x = self.linear2(x)
        return x
    
model = LinearRegressionModel()

In [71]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.9414],
         [ 0.5997],
         [-0.2057]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5087,  0.1390, -0.1224], requires_grad=True),
 Parameter containing:
 tensor([[0.1601, 0.0285, 0.2109]], requires_grad=True),
 Parameter containing:
 tensor([-0.2250], requires_grad=True)]

In [72]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [77]:
optimizer = optim.SGD(model.parameters(),lr=0.001)

In [94]:
epochs = 1000
for epoch in range(epochs+1):
    
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/20 Cost: 22310.925781
Epoch  100/20 Cost: 22310.925781
Epoch  200/20 Cost: 22310.925781
Epoch  300/20 Cost: 22310.925781
Epoch  400/20 Cost: 22310.925781
Epoch  500/20 Cost: 22310.925781
Epoch  600/20 Cost: 22310.925781
Epoch  700/20 Cost: 22310.925781
Epoch  800/20 Cost: 22310.925781
Epoch  900/20 Cost: 22310.925781
Epoch 1000/20 Cost: 22310.925781


In [80]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [98]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

dataset = TensorDataset(x_train, y_train)

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
model = nn.Linear(3,1)


optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [89]:
for i,data in enumerate(dataloader):
    print(i,data)

0 [tensor([[89., 91., 90.],
        [93., 88., 93.]]), tensor([[180.],
        [185.]])]
1 [tensor([[ 73.,  66.,  70.],
        [ 96.,  98., 100.]]), tensor([[142.],
        [196.]])]
2 [tensor([[73., 80., 75.]]), tensor([[152.]])]


In [99]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch% 100 == 0:
      print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, batch_idx+1, len(dataloader),
          cost.item()
          ))

Epoch    0/1000 Batch 1/3 Cost: 47030.316406
Epoch    0/1000 Batch 2/3 Cost: 11249.710938
Epoch    0/1000 Batch 3/3 Cost: 2125.012207
Epoch  100/1000 Batch 1/3 Cost: 0.246953
Epoch  100/1000 Batch 2/3 Cost: 1.019542
Epoch  100/1000 Batch 3/3 Cost: 0.052108
Epoch  200/1000 Batch 1/3 Cost: 0.695466
Epoch  200/1000 Batch 2/3 Cost: 0.030455
Epoch  200/1000 Batch 3/3 Cost: 0.224950
Epoch  300/1000 Batch 1/3 Cost: 0.743076
Epoch  300/1000 Batch 2/3 Cost: 0.074581
Epoch  300/1000 Batch 3/3 Cost: 0.049081
Epoch  400/1000 Batch 1/3 Cost: 0.259237
Epoch  400/1000 Batch 2/3 Cost: 0.521514
Epoch  400/1000 Batch 3/3 Cost: 0.191139
Epoch  500/1000 Batch 1/3 Cost: 0.281478
Epoch  500/1000 Batch 2/3 Cost: 0.468142
Epoch  500/1000 Batch 3/3 Cost: 0.000092
Epoch  600/1000 Batch 1/3 Cost: 0.236964
Epoch  600/1000 Batch 2/3 Cost: 0.087764
Epoch  600/1000 Batch 3/3 Cost: 0.824971
Epoch  700/1000 Batch 1/3 Cost: 0.582339
Epoch  700/1000 Batch 2/3 Cost: 0.077739
Epoch  700/1000 Batch 3/3 Cost: 0.009977
Epoch

In [104]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 

pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.8495]], grad_fn=<AddmmBackward0>)


In [106]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [108]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [109]:
dataset = CustomDataset()

dataset

In [111]:
dataset.__len__()

dataset.__getitem__(0)

(tensor([73., 80., 75.]), tensor([152.]))

In [ ]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [ ]:
nb_epochs